ALTER SCHEMA staging RENAME TO ingest;

ALTER TABLE ingest.imports ADD COLUMN state ingest.import_state NOT NULL DEFAULT 'queued';

CREATE TABLE ingest.batches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id bigint NOT NULL REFERENCES ingest.imports (id)
);
CREATE INDEX batches_import ON ingest.batches (import_id);
COMMENT ON TABLE ingest.batches IS 'Import batches';

GRANT SELECT ON ingest.batches TO rs_reader;
GRANT SELECT ON ingest.recent_imports TO rs_reader;
GRANT USAGE ON SEQUENCE ingest.batch_numbers TO rs_reader;
