-- A sequence created and dropped again.
CREATE SEQUENCE temp_seq;
COMMENT ON SEQUENCE temp_seq IS 'gone by the end';
GRANT USAGE ON SEQUENCE temp_seq TO PUBLIC;

-- A sequence renamed, then altered under its new name.
CREATE SEQUENCE ticket_numbers_old START 5;

-- A sequence dropped and created again under the same name.
CREATE SEQUENCE recycled_seq START 10;

-- serial and identity sequences, and sequences OWNED BY a column, of a
-- table the history drops.
CREATE TABLE widgets (
    id serial PRIMARY KEY,
    code bigint GENERATED BY DEFAULT AS IDENTITY,
    label text
);
CREATE SEQUENCE widget_labels OWNED BY widgets.label;
ALTER SEQUENCE widgets_id_seq RESTART WITH 100;
GRANT USAGE ON SEQUENCE widgets_id_seq TO PUBLIC;

-- Sequences owned by columns the history drops, and one detached from its
-- column before its table is dropped.
CREATE TABLE gadgets (
    id bigint PRIMARY KEY,
    legacy serial,
    counter bigint GENERATED ALWAYS AS IDENTITY
);
CREATE SEQUENCE gadget_batches;
ALTER SEQUENCE gadget_batches OWNED BY gadgets.legacy;
CREATE SEQUENCE gadget_serials OWNED BY gadgets.id;

CREATE TABLE doomed (id bigint);
CREATE SEQUENCE survivor_seq OWNED BY doomed.id;
